### model
model_name_or_path: EverAI-AI/glm-air-45-samu-sft-merged
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: jondurbin_truthy_dpo,flammenai_casual_dpo,raven_no_format_dpo,weyaxi_humanish_dpo
template: glm4_moe
cutoff_len: 8192
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
packing: false

### output
output_dir: saves/glm45air/lora/dpo_multi
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb

### train
deepspeed: examples/deepspeed/ds_z3_config.json
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100

### hub
push_to_hub: true
hub_model_id: EverAI-AI/glm-air-45-samu-dpo
hub_strategy: every_save

